---
- name: Add Apache alias
  hosts: prod
  become: yes
  tasks:
    - name: Copy alias file
      copy:
        src: alias.conf
        dest: /etc/httpd/conf.d
      notify: restart apache
  handlers:
    - name: Update httpd service
      service:
        name: httpd
        state: restarted
      listen: restart apache
